name: Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: astral-sh/setup-uv@v3
        with:
          python-version: '3.12'
          cache: true

      - name: Sync dependencies (frozen)
        run: uv sync --frozen

      - name: ruff format --check
        run: uv run ruff format --check src

      - name: ruff check
        run: uv run ruff check src

